name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install Jekyll and Dependencies
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'  # Ensure gems are installed inside vendor/
        bundle install --jobs 4 --retry 3
        echo "$(bundle info jekyll --path)/bin" >> $GITHUB_PATH  # Add Jekyll bin directory to PATH

    - name: Remove Unwanted Files
      run: rm -rf vendor/ _site/

    - name: Build the Site
      run: bundle exec jekyll build --destination _site

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v3

    - name: Deploy 🚀
      uses: actions/deploy-pages@v4
